name: sprint_debts
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_route: ^4.0.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  flutter_bloc: ^8.0.1
  flutter_hooks: ^0.18.4
  freezed_annotation: ^2.0.3
  injectable: ^1.5.3
  logger: ^1.1.0
  intl: ^0.17.0
  json_annotation: ^4.5.0
  retrofit: ^3.0.1+1
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^4.0.0
  build_runner:
  flutter_lints: ^1.0.0
  freezed: ^2.0.3+1
  injectable_generator: ^1.5.3
  json_serializable: ^6.2.0
  retrofit_generator: ^4.0.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/